name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: VistavkaApp/Dockerfile
          failure-threshold: error
          output-file: hadolint-report.txt

      - name: Upload Hadolint report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hadolint-report
          path: hadolint-report.txt


  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: BuildDocker image
        run: |
          docker build -t myapp:test -f VistavkaApp/Dockerfile .
          echo "Docker image built successfully!"

      - name: Test container
        run: |
          docker run --rm myapp:test echo "Container works!"

      - name: Save build log
        run: |
          echo "Build completed at $(date)" > build-log.txt
          docker images | grep myapp >> build-log.txt

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build-log.txt

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: VistavkaApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

